name: chips_choice
description: Lite version of smart_select package, zero dependencies, an easy way to provide a single or multiple choice chips.
version: 3.0.0
homepage: https://github.com/davigmacode/flutter_chips_choice

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
